### ISSUE TITLE
Review time-handling code: needs to be calendar-aware

### ISSUE THREAD

**Issue by agstephens** [roocs/34e-mngmt#76]
I experienced this error:

```
Traceback (most recent call last):
  File "/usr/local/anaconda/envs/rook/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 655, in parse
    ret = self._build_naive(res, default)
  File "/usr/local/anaconda/envs/rook/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 1241, in _build_naive
    naive = default.replace(**repl)
ValueError: day is out of range for month

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/anaconda/envs/rook/lib/python3.7/site-packages/roocs_utils/parameter/time_parameter.py", line 31, in _validate
    self._parse_times()
  File "/usr/local/anaconda/envs/rook/lib/python3.7/site-packages/roocs_utils/parameter/time_parameter.py", line 46, in _parse_times
    end, default=datetime.datetime(datetime.MAXYEAR, 12, 30)
  File "/usr/local/anaconda/envs/rook/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/local/anaconda/envs/rook/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 657, in parse
    six.raise_from(ParserError(e.args[0] + ": %s", timestr), e)
  File "<string>", line 3, in raise_from
dateutil.parser._parser.ParserError: day is out of range for month: 1861-02-30
```

Whilst not urgent to fix now, it highlights that using the standard `dateutil.parser` will not cope with non-standard calendar dates. Need to therefore review our entire stack for where this might be a problem.

**Comment by agstephens** [comment]
We think this is fixed by our `AnyCalendarDateTime` class.
